
-- Generated by ORDS REST Data Services 19.4.1.r0572045
-- Schema: COVID19JP  Date: 水 5月  06 04:22:09 2020 
--

BEGIN
  ORDS.ENABLE_SCHEMA(
      p_enabled             => TRUE,
      p_schema              => 'COVID19JP',
      p_url_mapping_type    => 'BASE_PATH',
      p_url_mapping_pattern => 'covid19jp',
      p_auto_rest_auth      => FALSE);
    
  ORDS.DEFINE_MODULE(
      p_module_name    => 'COVID-19',
      p_base_path      => '/patients/',
      p_items_per_page => 25,
      p_status         => 'PUBLISHED',
      p_comments       => NULL);

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'COVID-19',
      p_pattern        => 'csv/:municipality',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'COVID-19',
      p_pattern        => 'csv/:municipality',
      p_method         => 'GET',
      p_source_type    => 'plsql/block',
      p_items_per_page => 10000,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'declare 
  type cur_t is ref cursor; 
  c cur_t; 
  r_patient covid19_patients%rowtype; 
  l_munic_code number; 
  l_accept_type varchar2(80); 
begin 
  begin 
    l_munic_code := to_number(:municipality); 
  exception 
    when value_error then 
      l_munic_code := 0; 
  end; 
  if l_munic_code != 0 then 
    open c for select * from covid19_patients  
        where "全国地方公共団体コード" = l_munic_code order by line_no; 
  else 
    open c for select * from covid19_patients  
        where "都道府県名" = :municipality order by line_no; 
  end if; 
  owa_util.mime_header(''text/csv'', FALSE, ''utf-8''); 
  htp.p(''Content-disposition: attachment; filename="patients'' ||  
        utl_url.escape(:municipality, false, ''utf-8'') || ''.csv"''); 
  owa_util.http_header_close; 
  -- put BOM OxEF, OxBB, 0xBF 
  htp.prn(unistr(''\feff'')); 
  htp.prn(''"No",''); 
  htp.prn(''"全国地方公共団体コード",''); 
  htp.prn(''"都道府県名",''); 
  htp.prn(''"市区町村名",''); 
  htp.prn(''"公表_年月日",''); 
  htp.prn(''"曜日",''); 
  htp.prn(''"発症_年月日",''); 
  htp.prn(''"患者_居住地",''); 
  htp.prn(''"患者_年代",''); 
  htp.prn(''"患者_性別",''); 
  htp.prn(''"患者_職業",''); 
  htp.prn(''"患者_状態",''); 
  htp.prn(''"患者_症状",''); 
  htp.prn(''"患者_渡航歴の有無フラグ",''); 
  htp.prn(''"患者_退院済フラグ",'');                 
  htp.p(''"備考"''); 
  loop 
    fetch c into r_patient; 
    exit when c%notfound; 
    htp.prn(r_patient.LINE_NO); htp.prn('',''); 
    htp.prn(to_char(r_patient."全国地方公共団体コード",''000000'')); htp.prn('',''); 
    htp.prn(r_patient."都道府県名"); htp.prn('',''); 
    htp.prn(r_patient."市区町村名"); htp.prn('',''); 
    htp.prn(to_char(r_patient."公表_年月日",''YYYY-MM-DD'')); htp.prn('',''); 
    htp.prn(r_patient."曜日"); htp.prn('',''); 
    htp.prn(to_char(r_patient."発症_年月日",''YYYY-MM-DD'')); htp.prn('',''); 
    htp.prn(r_patient."患者_居住地"); htp.prn('',''); 
    htp.prn(r_patient."患者_年代"); htp.prn('',''); 
    htp.prn(r_patient."患者_性別"); htp.prn('',''); 
    htp.prn(r_patient."患者_職業"); htp.prn('',''); 
    htp.prn(r_patient."患者_状態"); htp.prn('',''); 
    htp.prn(r_patient."患者_症状"); htp.prn('',''); 
    htp.prn(r_patient."患者_渡航歴の有無フラグ"); htp.prn('',''); 
    htp.prn(r_patient."患者_退院済フラグ"); htp.prn('','');        
    htp.p(r_patient."備考"); 
  end loop; 
  close c; 
end;');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'COVID-19',
      p_pattern        => 'json/:municipality',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'COVID-19',
      p_pattern        => 'json/:municipality',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 10000,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select 
  LINE_NO as "No", 
  "全国地方公共団体コード", 
  "都道府県名", 
  "市区町村名", 
  "公表_年月日", 
  "曜日", 
  "発症_年月日", 
  "患者_居住地", 
  "患者_年代", 
  "患者_性別", 
  "患者_職業", 
  "患者_状態", 
  "患者_症状", 
  "患者_渡航歴の有無フラグ", 
  "患者_退院済フラグ", 
  "備考"        
from covid19_patients  
where 
  "都道府県名" = :municipality 
  or 
  to_char("全国地方公共団体コード") = :municipality
order by line_no');

  ORDS.DEFINE_TEMPLATE(
      p_module_name    => 'COVID-19',
      p_pattern        => 'q/:municipality',
      p_priority       => 0,
      p_etag_type      => 'HASH',
      p_etag_query     => NULL,
      p_comments       => NULL);

  ORDS.DEFINE_HANDLER(
      p_module_name    => 'COVID-19',
      p_pattern        => 'q/:municipality',
      p_method         => 'GET',
      p_source_type    => 'json/collection',
      p_items_per_page => 50,
      p_mimes_allowed  => '',
      p_comments       => NULL,
      p_source         => 
'select 
  LINE_NO as "No", 
  "全国地方公共団体コード", 
  "都道府県名", 
  "市区町村名", 
  "公表_年月日", 
  "曜日", 
  "発症_年月日", 
  "患者_居住地", 
  "患者_年代", 
  "患者_性別", 
  "患者_職業", 
  "患者_状態", 
  "患者_症状", 
  "患者_渡航歴の有無フラグ", 
  "患者_退院済フラグ",
  "備考"       
from covid19_patients  
where 
  "都道府県名" = :municipality 
  or 
  to_char("全国地方公共団体コード") = :municipality
order by line_no');

    
        
COMMIT;

END;