/*
 * データ更新処理を実行した履歴を書き込む
 */
CREATE TABLE  "COVID19_REFRESH_LOG" 
   (	
    "TABLE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"REFRESH_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"MUNICIPALITY_CODE" NUMBER
   )
/
