/*
 * 最後にデータを更新した時刻を保持する
 */
CREATE TABLE  "COVID19_LAST_REFRESH" 
   (	
    "TABLE_NAME" VARCHAR2(128) NOT NULL ENABLE, 
	"LAST_REFRESH_TIME" TIMESTAMP (6) WITH LOCAL TIME ZONE NOT NULL ENABLE, 
	"MUNICIPALITY_CODE" NUMBER
   )
/
